### PR TITLE
 Add swipeable actions to recycler actions

### PR DESCRIPTION
**Pull request by Alviere**

### CODE REVIEW

**Comment by Alviere** [comment]
Very strange. UI tests passed on the firebase, but CircleCI didn't get any response and failed with timeout after 10 minutes. I'll continue investigation.

**Comment by Alviere** [comment]
@jkaan Can you please merge changes from master to your branch so that we can trigger CI again?

**Comment by jkaan** [comment]
@Alviere Of course. I've done so now.

**Comment by VerachadW** [comment]
Not sure why the RecyckerView And ScrollView need swipe actions. Could you please explain? @jkaan

**Comment by jkaan** [comment]
@VerachadW I've had a test where I wanted to test that the moment that you start scrolling a certain event was triggered. I implemented that behaviour using a scroll listener on the recyclerview and the `scrollTo` functions on the RecyclerViewActions do not trigger the scroll listener.

**Pull request merged**
