### PR TITLE
Add hasTextColor matcher

### LINKED ISSUE #78: Add hasTextColor text view assertion
I wanted to test that my text view had a specific color or not. I saw that Espresso has a matcher for this called [hasTextColor](https://developer.android.com/reference/android/support/test/espresso/matcher/ViewMatchers.html#hasTextColor(int)).

Kakao does not yet have a wrapper for this.

### PR DESCRIPTION
**Pull request by jkaan**
Fixes #78.

It is basically a simple wrapper to the hasTextColor of Espresso.

### CODE REVIEW

**Comment by jkaan** [comment]
@VerachadW No problem at all. Thank you guys for making such an awesome library.

Do you know what's up with the CircleCI? It's been on 'Waiting for status to be reported' for like 10 hours or so now.

**Comment by vacxe** [comment]
@jkaan we will fix CI in the coming days. Thanks!

**Comment by vacxe** [comment]
@jkaan sometimes CiCircle not a stable. Could you update your PR through force push for trigger build again? Because unfortunately CiCircle don't provide any APIs for do it manually.

**Comment by jkaan** [comment]
@vacxe Did it now. Let's see what it does. Once it succeeds I'll remove the empty commit again.

**Comment by jkaan** [comment]
@vacxe seems that that also did not solve the issue. I'll remove the commit to trigger CircleCI again and see what it does.

**Comment by Alviere** [comment]
Let me try to resolve merging issue by reopening the PR

**Pull request closed without merging**
