### PR TITLE
Add Fit XY for test cases

### PR DESCRIPTION
**Pull request by lucas34**

### CODE REVIEW

**Comment by Vacxe** [comment]
@lucas34 API 25 works as expected. Crashed on 28
```androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with drawable id 2131165292 or provided instance' doesn't match the selected view.
Expected: with drawable id 2131165292 or provided instance
Got: "AppCompatImageView{id=2131230864, res-name=imgView, visibility=VISIBLE, width=1080, height=63, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=android.widget.FrameLayout$LayoutParams@1154caf, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0}"
```

**Comment by lucas34** [comment]
Ok that weird. From the code I don't see any specific code related to API level. Any idea what is causing this issue ?

**Comment by Vacxe** [comment]
@lucas34 from API 28 `.getDrawable()` from `ImageView` return not the same image as original one

**Comment by Vacxe** [comment]
@lucas34 even with force pushed changes it fails on API 28 +

**Comment by lucas34** [comment]
Yes I. was trying some solution. I saw that Fresco lib has an implementation of Scaled drawable to scale an underlaying drawable to a specific fit param.

**Pull request closed without merging**
